Issues#4~6に対応しました
Mami0223/MyFirstBB pull request #7
Opened 2023-01-07 11:26 UTC by Mami0223

アドバイス頂きありがとうございます。
Issues#4：is_numeric関数で型チェックし,bindParamを使ってクエリに変数を組み込みました。
Issues#5：画面に出すエラーは変数で制御に変更しました。ログファイルは日時、ユーザー名が追記される形に変更しました。
Issues#6：表示のタイミングでhtmlspecialcharsをかけました。
よろしくお願いいたします。

2023-01-07 14:50 UTC, hiroshiyamada requested changes

2023-01-07 14:50 UTC, hiroshiyamada commented on MyFirstBB.php
> +        error_log("コメントを入力してください（空白不可）", 3, "./" . $filePostDate. $error_link. "error.log");
error_logが重複しているようです。こちらが不要でしょうか？

2023-01-07 14:50 UTC, hiroshiyamada commented on MyFirstBB.php
> +    error_log($filePostDate. "_エラー種別:DB接続エラー\n", 3, "./error.log");
こちらのエラーログにも名前が必要ではないでしょうか？

2023-01-07 14:50 UTC, hiroshiyamada commented on MyFirstBB.php
> +    $error_name = $_POST["username"] ;//エラーログファイルの区別用
変数名がerror_nameだと、エラーの名前のように思えてしまいます。$user_nameの方がよいのではないでしょうか？

2023-01-07 14:50 UTC, hiroshiyamada commented on MyFirstBB.php
> +    if (!(empty($error_messages))) {
if($error_messages)の方がシンプルかと思います。

2023-01-07 14:50 UTC, hiroshiyamada commented on MyFirstBB.php
> +        echo '<script>location.href = "http://54.178.114.228/MyFirstBB/MyFirstBB.php" ;</script>';
location.href = "./MyFirstBB.php" でよさそうに思います。location.href = location.href でもいけるかもしれません。

2023-01-07 14:50 UTC, hiroshiyamada commented on utils/image.php
> +if (is_numeric($id)) {//文字が数値として有効な値であれば
文字が数値として有効な値でなかった場合に、エラーメッセージは出せないでしょうか？

2023-01-07 15:23 UTC, hiroshiyamada approved these changes
LGTM

2023-01-08 01:23 UTC, k2w4t4h commented on MyFirstBB.php
>                          <img src="<?php echo $imagesrc ?>" , width="250">
ここはif文の方にhtmlspecialcharsかけるんじゃなくて、$imagesrc側にかけないと意味がないかな。

もっとも、$imagesrcは上でプログラム的に定義されていて、idもDBから来ていてintであることが保証されているので、ここはhtmlspecialcharsしなくてもいいかもしれない。

丁寧にな話をすると、htmlspecialcharsは、
htmlspecialchars($comment["comment"], ENT_QUOTES | ENT_HTML5, "UTF-8");

って書いた方がいいんだけど、長くなるので、自作のエスケープ関数を作ってワンクッションかませといたほうがいいかもね。

2023-01-08 08:00 UTC, Mami0223 commented on MyFirstBB.php
>                          <img src="<?php echo $imagesrc ?>" , width="250">
コメントありがとうございます。

function.phpに自作エスケープ関数を作成して、$comment["username"]と$comment["comment"]のhtmlspecialcharsを置き換えました。($imagesrcはhtmlspecialcharsしないことにしました)

また、ついでにエラーログファイル作成の関数も作成したので、該当箇所を書き換えました。

どうぞよろしくお願いいたします。

2023-01-12 13:50 UTC, Mami0223 commented on MyFirstBB.php
> +if ($_POST["submitButton"]) {
レビューを頂きありがとうございました。

サーバーの設定でNoticeが出力されていなかったため、ご提示の方法で出力設定とし、if($_POST["submitButton"])部にもissetを加えました。

2023-01-15 08:30 UTC, k2w4t4h commented
問題ないと思います！

2023-01-16 06:30 UTC, merged